### ISSUE TITLE
If Github actions rendering fails, we should know about it

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#315]
Related to: 
https://github.com/AlexsLemonade/refinebio-examples/issues/312#issuecomment-713026482

Github actions rendering with `build-all` failed three times without us knowing about it because of a weird docker build fail that didn't really stop the docker building. 

We don't want fails to happen quietly, so we need to have system that sends us an alert if the render fails. Spell check sends alerts when it fails but perhaps this is because its required? - I'm not sure how this works, need to look into it. 

### Proposed solution(s)

I saw an example for [sending emails](https://github.com/spandanpal22/sending-alert-github-actions/blob/master/.github/workflows/send.yml) but they seemed to required a lot of `SECRETS` and set up. 

A slack notification might be the way to go? But what channel?
https://github.com/marketplace/actions/slack-notify

**Comment by cansavvy** [comment]
I found a more specific example for this: https://www.ravsam.in/blog/send-slack-notification-when-github-actions-fails/

**Comment by cansavvy** [comment]
I would need both Slack admin privileges and this repositories admin privileges to do this so this may need to wait. Here's the steps (as I specific as I understand them without having done it or seen these pages) that need to be done: 

- On Slack, we need to obtain the webhook url from the Incoming Webhook App (It's already set up and used on other channels) but I don't have app managing privileges so I'm not sure what this looks like specifically. I was looking at these instructions here: https://api.slack.com/messaging/webhooks#posting_with_webhooks
- It's unclear to me without seeing the app management page on Slack if a particular channel needs to have its own webhook or at least given permissions? I moderately suspect so. In this case, I set up a channel called `science-robots` that I've intended for alerts to be sent to. So if there are channel specific permissions they should be given to this channel. 
- This webhook URL needs to be provided to GITHUB secrets in settings for this repository as `ACTION_MONITORING_SLACK`: See instructions here: https://www.ravsam.in/blog/send-slack-notification-when-github-actions-fails/ and here: https://github.com/marketplace/actions/slack-notify#usage - it's not exactly clear to me how these work together and this may need some tests and reconfiguring. 

Then once that's set up, we can add this bit to end of ` docker-build-push.yml` (and probably also `docker-build.yml`?). 
```
      - name: Report render status
        if: always()
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }} 
          SLACK_MESSAGE: 'Rendering failed'
```
We'll need to do some tests to see if it works and also might want to do some refinement to tailor things more to our needs.
